### ISSUE TITLE
[BUG] Pokemon HeartGold and Black saves are not detected in GAMECART

### ISSUE THREAD

**Issue by lifehackerhansol** [d0k3/GodMode9#743] opened 2021-10-08 19:20 UTC
**Info about your system**
* O3DS XL
* Bootloader: GodMode9 2.0.0 release in FIRM0 and FIRM1 (was testing something unrelated, but can't think of why this would break anything)

**Help yourself**
Pokemon Black and Pokemon HeartGold save files do not show up in GAMECART.
The saves show up in Checkpoint, and return valid saves when played back via flashcarts, nds-bootstrap, and melonDS.

This was also reported with a SoulSilver cartridge over at Nintendo Homebrew. Their setup is b9s+luma -> GodMode9.

I am unsure of what else to test. I also do not see a particular issue with NDS saves post-2.0.0 release (if at all).

**Have you actually read this?**
[x] I have read the information above

**Comment by dratini0** [comment] 2021-10-10 14:03
Err, this is embarrassing. I have managed to reproduce this issue with my copy of Active Health. Which is an issue, because that was the cartridge I used to test when I "fixed" saves in cartridges with infrared in them. I will have some more time next Sunday to look more into this.

**Comment by dratini0** [comment] 2021-10-17 17:03
Okay, turns out I have fixed reading IR cartridges, but it hasn't been merged into `v2.0.0`. The commit is here: cc99734f

So, yes, it is entirely expected that you can't read saves from cartridges with IR in v2.0.0, but you can in snapshots. Does this match your observations?

**Closed as completed** 2021-10-17 19:23 UTC
Labels: bug
