### ISSUE TITLE
[Enhancement] GM9 FTP Server

### ISSUE THREAD

**Issue by GRX274** [d0k3/GodMode9#237] opened 2017-10-14 06:53 UTC
I'm Not Sure If This Is Possible But If You Can, But It Would Be Very Helpful

**Comment by ahoischen** [comment] 2017-10-14 08:13
This is a duplicate of #188 and #181. Please search *all* issues before opening one.

**Comment by d0k3** [comment] 2017-10-14 09:36
@ahoischen is right. And yeah, as always. I wish that was possible, but it isn't, and will most likely never be.

**Closed by d0k3** 2017-10-14 09:36 UTC

**Comment by GRX274** [comment] 2017-10-14 09:56
@d0k3 Would It Have Access Via The Godmode9 HBL Launcher? Because The OS Would Have Been Fully Loaded

**Comment by d0k3** [comment] 2017-10-14 10:36
No, the OS is unloaded in that case.
