### ISSUE TITLE
Godmode9 not displaying touch screen

### ISSUE THREAD

**Issue by aharay** [d0k3/GodMode9#475] opened 2019-04-07 14:56 UTC
When i launch my godmode9 i get the top screen perfect but it has no display on the bottom yet can still blindly access the menus

**Comment by d0k3** [comment] 2019-04-07 15:55
Duplicate of #466. The solution is to switch to fastboot3DS. See here for a quick and painless way:
https://github.com/d0k3/OpenFirmInstaller

**Closed** 2019-04-07 15:56 UTC
