### ISSUE TITLE
[BUG] DISA/DIFF DataAbort Crash

### ISSUE THREAD

**Issue by knight-ryu12** [d0k3/GodMode9#563] opened 2019-11-04 10:17 UTC
when you mount arbitrary created DISA/DIFF and trying to write to it, GM9 crashes without writing anything.

(This was reported on GM9 Discord; escalating into issue)

**Comment by d0k3** [comment] 2019-11-04 21:41
@aspargas2 - did you already see this? Got all the info you need?

**Comment by aspargas2** [comment] 2019-11-04 21:57
@d0k3  Yeah, I already saw all the relevant info in discord and am just finding time to look at it. Should have mentioned that here. I should be able to look at it today later ~~were his famous last words~~.

**Comment by knight-ryu12** [comment] 2019-11-04 21:59
I'm happy to provide more testing/data.

**Comment by d0k3** [comment] 2019-11-12 22:10
@aspargas2 and @knight-ryu12 - could you provide me with more info? Which files fail and how? And which ones already failed on v1.8.0? Also, got any more useful info?

**Comment by aspargas2** [comment] 2019-11-12 22:20
@d0k3 So the same files fail on latest that fail on 1.8.0, the only difference is that latest can read them just fine but data aborts on hash fixing due to lvl2_cache becoming null for seemingly no reason, while 1.8.0 fails to `extract DIFF data` on them with no data abort. I haven't investigated the behind-the-scenes details of the 1.8.0 failure yet. The files which fail are consistently any extdata files other than 00000000/00000001, the VXSE metadata file.

**Comment by d0k3** [comment] 2019-11-13 21:56
Could not reproduce this... can you name a specific file for which it happens?

**Comment by aspargas2** [comment] 2019-11-13 22:12
@d0k3 1:/data/<id0>/extdata/00048000/f000000b/00000000/00000002 (arbitrarily picked example), or any other extdata file that isn't 00000001. If you want to trigger the data abort with vdisadiff, you need to actually make a change to partitionA.bin before unmounting. For the 1.8.0 variant, failure happens as soon as you try to extract DIFF data on such a file.

**Comment by d0k3** [comment] 2019-12-10 22:25
Fixed by @aspargas2 - thank you!

**Closed by d0k3** 2019-12-10 22:25 UTC
Labels: bug
