### ISSUE TITLE
Bug Report: GM9 freezes when selecting Gamecart and no Cart is inserted 

### ISSUE THREAD

**Issue by wg93589** [d0k3/GodMode9#130] opened 2017-07-24 18:23 UTC
So, I was in GodMode9 and accidentally clicked on [C:] Gamecart while no game was inserted into the gamecart slot and it froze forcing me to hard reboot the 3ds.

EDIT: P.S This doesn't happen all of time.

**Comment by ValliantStorme** [comment] 2017-07-24 21:51
This happens consistently for me if the data on the cartridge is invalid (invalid header, invalid data, but there is a cartridge inserted)

**Comment by d0k3** [comment] 2017-07-24 22:30
Okay. Cart initialization is critical stuff after all. @wg93589 - can you try around and find out what may cause this to happen? Ie. what conditions have to be fulfilled so this happens?

@ValliantStorme - invalid cartridge data... What would that be, for example? Sky3DS, f.e. works.

**Comment by ValliantStorme** [comment] 2017-07-24 22:40
I'll have to dump my cart to tell you exactly what happened to it. It's a DS flash cart that I bricked while messing around, and also causes the HOME Menu to hang. Something's very wrong with it.

**Comment by d0k3** [comment] 2017-07-25 10:24
@ValliantStorme - if the DS flash cart itself is defective and it causes the same problems in home menu, there most likely is no solution. I do need further info from @wg93589, though.

**Comment by d0k3** [comment] 2017-07-27 00:22
@wg93589 - I need more info, otherwise I will have to close it. I can't reproduce this issue.

**Comment by d0k3** [comment] 2017-07-29 10:43
Okay, this is missing info, so I'll assume it solved on user side. @wg93589 - feel free to reopen if you can add more info to it / if it is still not solved. @ValliantStorme - as I wrote, if that cart borks the home menu, too, there's not really a chance I can handle it.

**Closed by d0k3** 2017-07-29 10:43 UTC
Labels: bug
