### ISSUE TITLE
Game dumping errors

### ISSUE THREAD

**Issue by Dudamax** [d0k3/GodMode9#126] opened 2017-07-20 02:38 UTC
Every time I try to dump a game like Pokemon which is over a gig I get the error insert content fails. However when I dump small games like virtual boy gba it works fine. I was reading a few articles about how it has to do with Godmode9 and it's accessible memory? Does anyone have a solution to this I need one so badly...

**Comment by d0k3** [comment] 2017-07-24 12:06
Can you give me more info? What exactly did you try to do, what is the exact error message, and what games does it happen with?

Keep in mind that games > 4GB *can't be copied to a FAT filesystem*. For these cases, the gamecart drives provides you with the split (.000 / .001) files.

**Comment by Dudamax** [comment] 2017-07-24 12:55
When I try to dump something like Pokemon or any other game greater than 1gb it gives the error "insert content failed" and then "build cia failed" (because I'm trying to dump a game for it's cia file). When I check the file in gm9/out it's only 14.3 kilobites

**Comment by Dudamax** [comment] 2017-07-24 13:00
Didn't see my first post sry but that's the only error I get with anything greater than 1 gig. I've tried with Mario kart 7 and super smash Bros and had no luck.

**Comment by d0k3** [comment] 2017-07-24 13:08
Alright, somethings fishy here... You're trying to dump from the gamecart, yes? And you use the untrimmed game file as base?

**Comment by Dudamax** [comment] 2017-07-24 13:55
If you're referring to the directory it's sysnand sd/title/00040000 and I try to build the cia from  the game's .tmd. I was trying to dump from an eShop file although I did try with my Pokemon x cart (1.71gb) and that gave an error too.

**Comment by d0k3** [comment] 2017-07-25 10:51
Okay, tried it with MK7 and SSMB and couldn't reproduce it. Works for me, I will need more info. Is your console somewhat special? What did you use to install those games? What region and type is your console and what is your entrypoint?

**Comment by Dudamax** [comment] 2017-07-25 13:09
I have an old 2ds (usa) and I'm using luma chainloader to go into GodMode9 copying and pasting of large files gives the error "Invalid directory object" but I also noticed that trying to enter [0] sdcard gives me the same error

**Comment by d0k3** [comment] 2017-07-25 14:13
That looks a lot like there's some issue on your SD card. Could you check / fix that SD card on a PC and then try again? On Windows command line that's chkdsk /f /x X: (where X is the drive of the SD card).

**Comment by AidenTheCuber** [comment] 2017-07-25 23:38
@Dudamax
Is your sd card on "lock"?

**Comment by d0k3** [comment] 2017-07-27 10:27
@Dudamax - did you try what I wrote in my last comment?

**Comment by Dudamax** [comment] 2017-07-27 15:22
@dok3 prior to my issue being posted here I asked the same thing on gba temp and someone recommended the same thing but it didn't help.

**Comment by d0k3** [comment] 2017-07-27 17:07
So... Is this card formatted with ExFAT maybe? One way or another, you will need to try another SD card or format this one in GM9.

**Comment by Dudamax** [comment] 2017-07-27 17:38
Ok I'll try to format it

**Comment by d0k3** [comment] 2017-07-30 10:38
@Dudamax - any news?

**Comment by d0k3** [comment] 2017-07-31 22:26
Okay, closing this now, assuming @Dudamax got it solved. @Dudamax - if it is not solved now, reopen it, please.

**Comment by Dudamax** [comment] 2017-08-01 13:08
No luck after formating. I even tried another SD card and that didn't help.

**Comment by d0k3** [comment] 2017-08-01 13:39
Okay, we can try to get this solved, but you need to give me info sufficiently fast. There is something you are doing wrong. Did you format the SD card via GodMode? Can you browse it's contents in GM9? If that other SD card failed, too, maybe it's of the same manufacturer / type?

**Comment by Dudamax** [comment] 2017-08-03 11:31
My main SD is a Sony sdxc 64gb and the second is a sandisk sdhc 16gb but I'll see if I can get another SD card to test with

**Comment by d0k3** [comment] 2017-08-07 21:38
@Dudamax - can you retry with the most recent release?

**Comment by d0k3** [comment] 2017-08-08 11:32
This also one of these edge cases which ar ejust not reproducable. @Dudamax - you seriously need to find out what you do differnet than anyone else. I hope the `help wanted`tag will bring other people on here who can shed some light.

**Comment by Dudamax** [comment] 2017-08-08 22:34
I did try version 1.3.0 and still have the same error.

**Comment by Dudamax** [comment] 2017-08-08 22:34
Thanks for doing that.

**Comment by d0k3** [comment] 2017-08-10 10:56
Okay, we'll try this differently.

@Dudamax - here's a build with some debug outputs:
https://transfer.sh/UqO2c/GodMode9-20170810-105629.zip

Can you run this and tell me what output you get before it fails for you?

**Comment by Dudamax** [comment] 2017-08-10 12:56
It first says it is successful in opening the .app I try to dump. Then it's says "main loop result: 1", "finished: 1" and then insert content failed and build cia failed

**Comment by d0k3** [comment] 2017-08-11 20:47
Okay, thanks, looking into it. I guess we need another test build. Expect one shortly.

**Comment by d0k3** [comment] 2017-08-11 20:50
Actually, you can help me a bit. How long does it take until you get the "main loop result: 1"? Immediately? Or does it take rather long?

**Comment by Dudamax** [comment] 2017-08-11 20:58
The dump has very little progress by the time I get the error.

**Comment by d0k3** [comment] 2017-08-11 21:24
Hmm, okay, an idea. Use the latest release, but get that aeskeydb.bin file (A5B28945A7C051D7A0CD18AF0E580D1B, search for it), and put it into sd:/gm9/support,. Then retry.

Also, in terms of seconds (or minutes) - how long does it take?

**Comment by Dudamax** [comment] 2017-08-11 21:41
I was able to find aeskeydb.bin (didn't check the md5 but it was 1024 bytes) and I'm still getting the error though it is a little quicker. It takes around 5 seconds when the process starts.

**Comment by d0k3** [comment] 2017-08-13 17:34
Can you try this one then?
https://transfer.sh/fWxG6/GodMode9-20170813-113402.zip

**Comment by d0k3** [comment] 2017-08-14 09:53
Okay, you haven't responded yet, but here's one that will be even more helpful than the previous one:
https://transfer.sh/6w66T/GodMode9-20170814-095345.zip

This has additional debug output and will help me pinpoint the exact location where the issue happens.

**Comment by Dudamax** [comment] 2017-08-14 14:18
I didn't get any debug outputs on the 20170813 build. On the 20170814 build I did get "fail code: 6"

**Comment by d0k3** [comment] 2017-08-14 20:53
Okay, that means the problem is actually with writing, and as no one but you has that error, this very much looks like a hardware quirk. What about copying large files around? Is there trouble with this? And, if GodMode9 gives you trouble in copying large files around, could you try an alternative file manager (CTRXplorer, for example).

**Comment by d0k3** [comment] 2017-08-17 00:21
Okay, this should give us the insight to finally understand this problem:
https://transfer.sh/dXnHE/GodMode9-20170817-001828.zip

Please also tell me what game you tried it with.

**Comment by Dudamax** [comment] 2017-08-17 00:29
Write error code: 1 and I tried with Pokemon moon

**Comment by d0k3** [comment] 2017-08-17 00:54
Okay, I'll try to tell you what this means. Error code 1 means FR_DISK_ERR, which is bad. That's a low level disk error, and normally that would mean a defective SD card. If you really tried with two SD cards, though, the issue is one level deeper, which means the SD card reader / writer in you console.

Now, no need to give up right away. Could you try cleaning that SD card slot? High purity isopropyl alcohol or compressed air are options to do so. Maybe even a vacuum cleaner (no joking, did that myself on otehr occasions, too).

If that doesn't help, try to make a similar issue happen somewhere else - f.e. when loading a title from the system OS. Maybe you've still got warranty.

In any case, make absolutely sure that issue happens on both SD cards you tried.

**Comment by d0k3** [comment] 2017-08-18 13:09
Alright, closing this now. As I wrote, the issue is in your console, try to fix it. Also, feel free to reopen this if something comes up.

As for that issue in your card reader, you can ask around about this on the usual locations, or join us on IRC (freenode Cakey), where you will find people knowing more about that hardware stuff than me.

**Closed by d0k3** 2017-08-18 13:09 UTC
Labels: help wanted

**Comment by Dudamax** [comment] 2017-08-18 14:00
Yes thanks I was able to fix the problem. The first two SD cards I tried
were defective. The third one I tried was a SanDisk and I was able to dump
the games I needed.

**Comment by urherenow** [comment] 2018-05-30 14:48
You should first use discord or a forum for help, until/unless you confirm there’s a bug. I’d make a 1:1 dump with Gateway’s launcher first, then use decrypt9WIP, personally.

**Comment by SirNapkin1334** [comment] 2018-05-31 01:04
@Noobie6942 ask for help on the [GodMode9 Discord](https://discord.gg/EGu6Qxw)
