### ISSUE TITLE
[BUG] Screenshot doesn't work

### ISSUE THREAD

**Issue by pixthehe** [d0k3/GodMode9#779] opened 2022-07-19 19:31 UTC
---
name: Bug report
about: the screenshot function in gosmode9
title: "[BUG] screenshots don't work"
labels: bug
assignees: ''

---

So I pressed r+l and then I looked for the png in gm9/out and found it and the I tried to view the png and it says an error happened. I transferred the png to my computer and it looked corrupted.

I am running the latest release of luma and Godmode along with boot9strap on a new nintend 3ds xl.

**Comment by d0k3** [comment] 2022-07-21 19:34
I just tried it and couldn't reproduce it.

It's highly unlikely this is actually a GM9 bug. The culprit is rather a full or failing SD card, or, even worse, faulty 3DS cart writer hardware (Nintendo didn't build those for eternity, sadly). I'm closing this now, but feel free to reopen after you throughly checked (chkdsk is your friend) or even replaced that SD card and this keeps on happening.

**Closed by d0k3** 2022-07-21 19:34 UTC
Labels: bug

**Comment by pixthehe** [comment] 2022-07-21 20:04
Should I move the contents of my sd card to another and try again?

**Comment by d0k3** [comment] 2022-07-21 21:16
Yes, you could do that. And no, the issue is most likely in your SD card. Also keep in mind GM9 can't display it's own screenshots, cause those are bigger than the width / height limit.
