### ISSUE TITLE
Some cartridges are dumped with an incorrect file size

### ISSUE THREAD

**Issue by ghost** [d0k3/GodMode9#433] opened 2018-10-03 12:26 UTC
The version of GodMode9 I'm using is GodMode9-v1.7.1-18-g8f24ccec-20180925030010, though I believe this issue is also present in the latest stable version.  

When dumping untrimmed .3ds files from cartridges (Both encrypted and decrypted), GodMode9 sometimes leaves off the final byte of the file.  I dumped 15 games and had this happen twice - on Pokémon Moon, and on Donkey Kong Country Returns 3D.  Both of these games are 4 GB in size, and are the only games I have at that size, so it may be related to that.  

To be clear:  The correct dump is meant to be 4294967296 bytes, and GM9's dumps were 4294967295 bytes, missing the final byte of padding.  

Semi-relatedly:  I'm using a dev version because the latest stable version was producing incorrect dumps for many of my cartridges (Not the same issue noted above).  I'm happy to report that the dev version I'm using did fix all of the dumping errors the stable version was giving me, with the exception of the one detailed above.  Of 30 dumps between 15 cartridges (Encrypted and decrypted each), I went from 13 incorrect dumps in the stable version to 4 in this one, with those 4 being from the issue mentioned above, that was easy to fix by hand.

**Comment by d0k3** [comment] 2018-10-03 13:13
Well written issue, 5 stars for that. But... This is not really a bug but rather a limitation of the FAT file system. 4GiB - 1 is the maximum size of a file. As the last byte is always just padding, we leave it out silently. Only other solution would be split files, and you don't want that (obviously).

Can you give me more info about that other issue? What was wrong with those dumps?

**Comment by wbmfvztm** [comment] 2018-10-04 03:37
That's a bit unfortunate about the FAT limitations - that missing byte messes with the hashes I use to verify the game files.  But understandable.  

I'm pretty sure the other issue I was having with the stable version was identical to this issue:  https://github.com/d0k3/GodMode9/issues/413

When I made a decrypted dump of Majora's Mask 3D, the version GodMode9 made had 212 bytes of data starting at position 003B6D2C, while the correct dump had all zeroes in that range, but the two were otherwise identical.  This seems similar to what was reported in that thread, though the CRC32 hash for my file was different than theirs - Mine was 7C0B4968.  

This is fixed in the dev version I used - and the dev version also fixed all of my encrypted dumps that were also coming out incorrectly.  I could give more details here if you want - games, hashes, what changed between versions, those 212 bytes of data, etc - but I assume since the issue is already fixed you're not after a ton of detail here.  

Also, so I'm clear:  When I say the dumps came out "incorrectly" I mean they're still fully playable in an emulator, their hashes just don't match hashes for known good dumps of the same games.  They all had some extra junk data for some reason.  I had someone else I asked about this speculate it was the game's private header, but I don't really know for sure.

**Closed as completed** 2018-10-04 09:27 UTC

**Comment by wbmfvztm** [comment] 2018-10-04 15:05
I agree your current solution is much better than splitting the files.  

I'd like to clarify from my previous post, in case it came across the wrong way:  When I said it was "not at all hard to fix once you know what's happening", I meant from my end of things - I recognize and accept that GM9's current way of handling 4GB files is the best possible method in these circumstances, and was just making the statement that it's not hard for me to add 'FF' to the end of the file in a hex editor now that I know what's causing the hash discrepancy.  I don't _think_ you took it the wrong way but I just wanted to make sure.  

Cheers!

**Comment by d0k3** [comment] 2018-10-04 15:40
Didn't take it the wrong way, don't worry :). You did notice, though, that GM9 also offers the split files to download from the cart? 

I myself prefer the 4GiB - 1 files, too, though.
