### ISSUE TITLE
Crashes after launching at boot

### ISSUE THREAD

**Issue by schmoke** [d0k3/GodMode9#550] opened 2019-10-18 01:37 UTC
After i hold down start and power to boot with gm9, it crashes at the RTC Date&Time screen. Doesnt allow any buttons or operations other then power button. Also blue line on the top of my screen.

**Comment by HIDE810** [comment] 2019-10-18 08:19
I'm in a similar situation. This happens when I use a gamecart. Without it, gm9 works fine.

**Comment by Wolfvak** [comment] 2019-10-18 15:21
Does it change the screen brightness if you move the volume slider?

**Comment by d0k3** [comment] 2019-10-18 17:00
@schmoke & @HIDE810 - a photo or even a short video (better) would help a lot here.

**Comment by schmoke** [comment] 2019-10-18 23:37
blue line on the top screen
and says dump error. @d0k3

**Comment by Wolfvak** [comment] 2019-10-18 23:39
Please send a picture of it, what you just said makes no sense.

**Comment by HIDE810** [comment] 2019-10-19 13:39
@schmoke - my situation may be different from yours. I have no blue line and no dump error.

On godmode9 v1.9.0, when launching gm9 with setting a gamecart, I have to wait a few seconds to operate.
e.g.
- nintendogs+cats(JPN) - about 2.5 seconds
- MonsterHunterX(JPN) - about 10 seconds

Without a gamecart, gm9 can be used immediately.

tested:
new3ds, 11.10.0-43J, godmode9 v1.9.0 via fastboot3ds

Interestingly, when tested old3ds(11.10.0-43J, godmode9v1.9.0 via b9s+luma chainloader), this does not happen.

**Comment by d0k3** [comment] 2019-10-19 17:55
@dratini0 - @HIDE810's problems sound a lot like they could be their origin in the most recent changes to the gamepad code. Maybe some timeouts need to be lower?

And, @HIDE810 - thank you!

**Comment by dratini0** [comment] 2019-10-19 23:35
Okay, yes, that does seem excessive. I will get around to adjusting those delays later this week.

**Comment by d0k3** [comment] 2019-10-20 11:00
@dratini0 - maybe some kind of "lazy" init would be possible, too? Meaning: Do these time consuming savegame specific inits only when the savegame file is actually accessed.

@HIDE810 - can you try this testbuild?
https://f.secretalgorithm.com/hhhmY/godmode9.firm
Important info: This is a workaround more than a fix, it just increases the splash duration, which makes sure we don't get any wrong cart insert detects. When you actually enter the gamecart drive, you'll still get that excruciating delay. That means: even if that fix helps, we will still need you around for testing.

**Comment by HIDE810** [comment] 2019-10-20 12:20
@d0k3 
> This is a workaround more than a fix, it just increases the splash duration, which makes sure we don't get any wrong cart insert detects. When you actually enter the gamecart drive, you'll still get that excruciating delay.

Yes, it worked as you said.

**Comment by dratini0** [comment] 2019-10-20 22:47
@d0k3 Not really, it has to be done with gamecart init, as it needs to ID the flash to know the size to display. The best solution I can come up with is to set the timeout really short (100 ms or even 0?) - to be fair if it is in a write or erase cycle when you boot, it's probably broken.

**Comment by d0k3** [comment] 2019-10-21 13:47
I trust your judgement on that, @dratini0

@schmoke - we still need more info from you. Can't do much with the description you gave us, and your issue is different from the one @HIDE810 reported.

**Comment by d0k3** [comment] 2019-10-26 12:20
Okay, @dratini0 fixed the cart related stuff in the latest commit. @HIDE810 - if some issues persist, pls open a new issue - this one was abotu something else from the start. You may test, here's a test build:
https://f.secretalgorithm.com/Js57/godmode9.firm

As for @schmoke - we haven't heard back from you in a week, and you bug report didn't contain enough info for us to do anything. Feel free to continue writing here or open a new issue. Until then, we're assumin this solved. Issue closed.

**Comment by schmoke** [comment] 2019-10-31 16:48
Hey sorry i forgot i made the post. My 3ds is still in shambles. Every time i start i either get this, (reference image) or it lets me set my clock and whatnot in godmode launch, then it freezes.
![IMG_3728](https://user-images.githubusercontent.com/56706109/67967874-5ccba800-fbd4-11e9-8c5f-b443c69db7ab.JPG)

**Comment by aspargas2** [comment] 2019-10-31 17:24
Uh.... That looks like the bottom screen of a Luma crash, meaning somehow either GodMode9 is crashing before it sets up the exception vectors, or it's rebooting in such a way that causes Luma to crash on the next boot. I find the former more likely, but still very weird.

**Comment by aspargas2** [comment] 2019-10-31 17:28
@schmoke, could you try booting GodMode9 through something other than Luma? Assuming you're using boot9strap, the easiest way to do that would be to temporarily copy `GodMode9.firm` to the SD root, rename `boot.firm` to something like `luma.firm`, then rename `GodMode9.firm` to `boot.firm`.

**Comment by schmoke** [comment] 2019-10-31 18:10
Yes Ill try when im home, is there an easier way to talk? Discord?

**Comment by aspargas2** [comment] 2019-10-31 18:13
Yeah, if you'd rather do that, the invite to the gm9 discord is in the readme. All the devs are there, mostly in the #irc channel.

**Comment by SirNapkin1334** [comment] 2019-10-31 23:46
(Now the #general channel)

**Comment by schmoke** [comment] 2019-11-01 22:05
Please link it, as I cannot find it in the readme

**Comment by Wolfvak** [comment] 2019-11-01 22:15
@schmoke https://discord.gg/EGu6Qxw

**Comment by d0k3** [comment] 2019-11-01 23:25
Okay, reopening this until we know the cause.

**Comment by Wolfvak** [comment] 2019-11-01 23:30
For posteriority, that exception dump was done by Luma, so GM9 itself failed to get to the `main` function.

I have a suspicion it isn't even executing at all, so it _could_ be a bug in luma's FIRM loader, but since it doesnt happen for anyone else I don't know exactly what happens. Might be a corrupt FIRM that just so happens to be able to trigger an untested code path in the FIRM loader.

**Comment by d0k3** [comment] 2019-11-08 18:49
Are we even responsible for this? Can we even do anything about it? @Wolfvak - what's your opinion?

**Comment by Wolfvak** [comment] 2019-11-08 18:58
Closing this as OP hasn't gotten back to us after a week of waiting.

**Closed by Wolfvak** 2019-11-08 18:58 UTC
Labels: bug
