### ISSUE TITLE
Random freezing on boot

### ISSUE THREAD

**Issue by dogtopus** [d0k3/GodMode9#30] opened 2017-03-13 17:12 UTC
Since v1.0, GM9 freezes a lot during boot. 0.9.2 works fine.
I am using AuroraWright's fork of A9LH on an O3DS
Also seems that similar problem also exists in latest Decrypt9WIP

**Comment by d0k3** [comment] 2017-03-13 17:56
This is strange, I can't reproduce it. First, try the latest hourly:
https://transfer.sh/15Pe7d/godmode9-20170313-175517.zip

If that still freezes, we need to get behind this. In that case I will make special build with debug output that you'd have to run.

**Comment by dogtopus** [comment] 2017-03-13 23:01
> if you could tell me at which point latest D9WIP freezes

It freezes with a complete black screen (even no screeninit). Tried to press buttons and got no response (not only a display issue). Same for GodMode9

> First, try the latest hourly

Will try this later

**Comment by Jerry-Shaw** [comment] 2017-03-13 23:31
Met the same problem last week, when I was doing lots of shutdown and power on, loading Godmode9 via ctrbootmanager9. But not many. When I try Decrypt9, all succeeded.

**Comment by dogtopus** [comment] 2017-03-14 01:54
Just compared the latest code of GM9 and D9WIP and found [something](https://github.com/d0k3/Decrypt9WIP/blob/master/source/start.s#L86)
This was fixed in latest master of GM9 but not merged into D9WIP yet.
Maybe that's the cause?

**Comment by d0k3** [comment] 2017-03-14 10:24
So... the edit of the start.s file fixed it in GM9? It's very much possible the last edit to this actually caused this.

**Comment by Jerry-Shaw** [comment] 2017-03-14 11:56
Should we do more tests on it? Or is there some dev version?

**Comment by d0k3** [comment] 2017-03-14 14:39
Well, first try if it still happens in the latest hourly, @Jerry-Shaw

**Comment by Jerry-Shaw** [comment] 2017-03-15 14:19
Compiled by myself from the latest commit, version 1.0.5, tested for 10 times' hot boot via ctrbootmanager9 and 10 times' cold boot via ctrbootmanager9, all succeeded. Good.

**Comment by d0k3** [comment] 2017-03-16 09:16
@dogtopus - could you also test the latest hourly and tell me if it is fixed? I'll add these fixes to D9 / H9 / SafeSigHaxInstaller if they work.

**Comment by dogtopus** [comment] 2017-03-16 14:00
> could you also test the latest hourly and tell me if it is fixed?

> The latest hourly seems working. Already did 10+ reboots and no freeze.

I haven't seen any freezes since that, so it was likely fixed.

**Comment by Wolfvak** [comment] 2017-03-16 15:11
For the record...

```
Feb 25 11:37:52 <d0k3>	Oh, you already sent that pr?
Feb 25 11:38:01 <Wolfvak>	yes
Feb 25 11:38:20 <Wolfvak>	as well as a hotfix for GM9 which should also be applied to all of your other projects...
Feb 25 11:38:35 <d0k3>	Oh noes...
Feb 25 11:38:54 <d0k3>	But, well, as of now, that is only D9 and GM9, I guess
Feb 25 11:39:06 <d0k3>	HG9 has only one entrypoint
Feb 25 11:42:27 <d0k3>	Hmm, where is that hotfix?
Feb 25 11:42:41 <Wolfvak>	https://github.com/d0k3/GodMode9/pull/27
Feb 25 11:42:47 <d0k3>	Got it, thanks
Feb 25 11:43:06 <Wolfvak>	its relatively harmless because usually __end__ == __bss_end
Feb 25 11:43:25 <Wolfvak>	but if someday you decide to add symbols after __bss_end or something... fun stuff would happen
```

turns out "fun stuff" actually happened...

**Comment by d0k3** [comment] 2017-03-22 12:43
Fixed, closing it now.

**Closed by d0k3** 2017-03-22 12:43 UTC
