### ISSUE TITLE
Separate the Cart2 save data from the .3ds when dumping cart

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#380] opened 2018-06-01 07:34 UTC
Feature request: Separate the Card2 save data from the .3ds, like with the unique data (the """gateway header""") that exists in an unused ROM. When copying across the .3ds from GAMECART, the Card2 should be blanked with FF.

Crappy Tiny Reader correctly blanks out this data: http://scene.releases.free.fr/index.php?p=tools

**Comment by d0k3** [comment] 2018-06-01 15:39
Have you actually tried dumping a card2 gamecart before opening this issue? If not, do so (or let someone else do it for you), then come back. I guess you will close this issue then.

**Comment by mariomadproductions** [comment] 2018-06-01 15:57
Someone else has, and has reported that the Card2 save data was present.

**Comment by d0k3** [comment] 2018-06-01 17:01
Source? Was he really using an up to date GM9? What game?

**Comment by Hking0036** [comment] 2018-06-03 05:48
Dumped a copy of Pokemon Y 2 days ago, latest version (1.6.3) and the Card2 save wasn't pulled out.

**Comment by Hking0036** [comment] 2018-06-04 03:08
Just got done dumping Pokemon Y again, seems to be fixed! Thanks.

**Comment by Jakz** [comment] 2018-06-04 12:34
Hello, I was the one that reported the issue on EUR version. I'll try if it's fixed later and let you know.

**Comment by d0k3** [comment] 2018-06-04 23:03
@Jakz - nice avatar :). Yeah, it should be fixed, but it would be great if you could test, too.

**Comment by Jakz** [comment] 2018-06-11 14:47
Thanks for the avatar ;)
Just dumped Animal Crossing - New Leaf (which is Cart2 type) and I can confirm that it looks like clean.

**Comment by d0k3** [comment] 2018-06-13 11:35
Alright, thanks!

**Closed by d0k3** 2018-06-13 11:35 UTC
