### ISSUE TITLE
Godmode9 cannot encrypt/decrypt/build CIA from file

### ISSUE THREAD

**Issue by Lglaplante** [d0k3/GodMode9#439] opened 2018-10-21 12:41 UTC
Godmode9 can no longer build CIA's from a .3DS, nor decrypt or encrypt one

**Comment by urherenow** [comment] 2018-10-21 17:49
What are you talking about? You give no info about your setup, and you’re probably either missing or have a corrupt aeskeydb.bin.

**Comment by d0k3** [comment] 2018-10-21 21:50
Not able to reproduce this on the latest nightly, @Lglaplante - is it possible your .3DS file is defective? You need to give us more info.

**Comment by Lglaplante** [comment] 2018-10-22 03:26
I'll look into that a bit further, but I tried with multiple .3DS files. Any of the options in NCCH options aren't working on my side. I'll try with a .cia converted to .3DS q

**Comment by Lglaplante** [comment] 2018-10-22 03:27
@urherenow aeskeydb.bin isn't needed on Old3DS apparently (and with the latest versions of Luma3DS)

**Comment by urherenow** [comment] 2018-10-22 07:05
That’s why you should state your model, firmware version and CFW version when you open a ticket.

**Comment by d0k3** [comment] 2018-10-22 10:52
@Lglaplante / @urherenow - `aeskeydb.bin` is in general no more needed with boot9strap or fastboot3ds. In these cases it's only needed for some very specific operations (stuff you most likely don't want to do anyways).

**Comment by Lglaplante** [comment] 2018-10-22 12:40
I'll try tonight with different .3ds files and different godmode versions 
I am not the only one also to have this issue, I've seen a couple people having the same issue
I'll gather information from them

**Comment by d0k3** [comment] 2018-10-23 20:33
@Lglaplante - got any news already? You'd already help me if you tell me which .3ds files didn't work.

Also, check if you have enough space free on your SD card. Insufficient space is a likely cause of failure.

**Comment by Lglaplante** [comment] 2018-10-23 20:58
Oh yeah I got plenty of space as of the time I tested
I'll check if i DO have enough space for two files
I thought godmode deleted the .3ds after, that might be why it isn't working

**Comment by Lglaplante** [comment] 2018-10-24 00:44
Update: I tested with a Ocarina Of time .3DS (wich weight around 500MB) I have 6,2 GB left
I got the error on all of the options

**Comment by d0k3** [comment] 2018-10-24 09:39
Did you use the latest nightly?
https://d0k3.secretalgorithm.com/

Also, what errors do you get?

**Comment by d0k3** [comment] 2018-10-25 10:54
@Lglaplante - maybe you want to do a video of an attemtp to convert and upload it somewhere? That may be the easiest way to find out what's wrong.

**Comment by Lglaplante** [comment] 2018-10-25 11:29
For the first comment: I don't get any error codes. It just says: "Encryption/Decryption Failed" or "Couldn't build cia". I tried verifying the file, but it also doesn't work.
For the video, I will record it later today and link it down here

**Comment by d0k3** [comment] 2018-10-25 11:39
You may also check if you have some `aeskeydb.bin` file inside `0:/gm9/support`. If you have a corrupted one, that may be the cause of failure. Your SD card may be broken, too, so you could try building a CIA directly from a game cartridge.

**Comment by Lglaplante** [comment] 2018-10-25 13:04
Aeskeydb.bin shouldn't be corrupted
SD card isn't broken too

**Comment by Ammako** [comment] 2018-10-26 20:55
Cross-reference your files with no-intro (check the checksums for the files that you've transferred to your SD card, not the ones on your PC, in case your SD card reader is at fault.)

https://datomatic.no-intro.org/?page=show_record&s=64&n=0033
https://datomatic.no-intro.org/?page=show_record&s=64&n=1259

Even one single byte of the file being corrupted will prevent the verification from succeeding, though I'm not sure how much corruption there would need to be for the CIA building and decryption/encryption to fail.

This might not be the cause of the problem, but it's probably good to rule that out nonetheless.

**Comment by Lglaplante** [comment] 2018-10-29 02:29
I actually have no gm9/support folder (nor any gm9 folder except gm9out)

Also it might be the copying to sd card process that could've maybe broke the file...
I tried with another clean dump of my ocarina of time game and all options worked real fine (tho they didn't like a week ago)

I guess this issue can be closed as it seems to be on my side and not on gm9 side

**Comment by d0k3** [comment] 2018-10-29 11:08
Alright, I'm closing this now. Feel free to reopen or add comments to this issue if it should happen again.

Also, *check your SD card for corruption*. Windows `chkdsk` can help and so can [h2testw](https://www.heise.de/download/product/h2testw-50539).

**Closed by d0k3** 2018-10-29 11:08 UTC

**Comment by drq-spec** [comment] 2020-04-07 09:10
Hello I have the same problem my 3ds does not want to convert my .3ds files to .cia under godmod9. She tells me about a failed operation. Can you help me.

cordially.

**Comment by Gillogster** [comment] 2020-04-10 00:51
Had this issue 
Turned off read-only on the 3ds file 
Verified and fixed
CIA conversion finally worked
I was tipped off by the fact that I couldn’t delete these 3ds files in GM9, seemed like a permissions issue to me, sure enough read only was enabled on the files I was trying to install

**Comment by OzRangers** [comment] 2020-04-24 22:55
> Had this issue
> Turned off read-only on the 3ds file
> Verified and fixed
> CIA conversion finally worked
> I was tipped off by the fact that I couldn’t delete these 3ds files in GM9, seemed like a permissions issue to me, sure enough read only was enabled on the files I was trying to install

Other than this, is there a different troubleshooting you might advise doing? I did check that my 3ds files had its Read only check off. Still I get the Failed Operation error

**Comment by Sulick-e** [comment] 2020-04-28 22:44
Well, today I have tried to install a .3ds file, the Inazuma Eleven Go Galaxy Supernova in english, a translation made by fans, the thing is, when i click to transform it to .cia, it says failed, when I try to encrypt or decrypt, the same, failed. I have a lot of space still, last version of godmode9, no aeskeydb.cin files in 0:/gm9/support  . I don't know what happens, y need helps, THANKS

**Comment by OzRangers** [comment] 2020-04-29 00:24
> Well, today I have tried to install a .3ds file, the Inazuma Eleven Go Galaxy Supernova in english, a translation made by fans, the thing is, when i click to transform it to .cia, it says failed, when I try to encrypt or decrypt, the same, failed. I have a lot of space still, last version of godmode9, no aeskeydb.cin files in 0:/gm9/support . I don't know what happens, y need helps, THANKS

Hey instead of converting them, try to create a CIA, within godmode, I will send you some screenshots later on today

**Comment by d0k3** [comment] 2020-05-06 15:54
@Sulick-e @OzRangers - Verify the .3DS file in GM9. If it has any fixable errors, it will offer fixing.
