### ISSUE TITLE
Formatted SD naming suggestion

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#282] opened 2017-12-24 03:22 UTC
Hey, since I name my 3DS's SD cards after what system they are, I thought it would be nice to have the default SD name be you're console's system, i.e. O3DS or 3DSXL or N2DSXL, etc. I highly doubt that anybody names their SD card GM9SD, but I'm sure many people name it the above thing. It's a small, but convenient idea.

**Comment by d0k3** [comment] 2017-12-25 00:44
You can already enter the name in the label tool, no? Maybe you mean the preset in that dialogue?

**Comment by SirNapkin1334** [comment] 2017-12-25 15:42
Yes. I mean the preset. Considering GM9's typing system is...well, clunky, it'd be nice to have that as a default, so myself and probably many other people don't have to slowly type it in.

**Comment by pthfdr-42** [comment] 2017-12-27 04:13
> as a default
My opinion is to use the label `CTR-_______`, where the underscores are random capital characters, as only caps should be used in the 11-byte FAT label.CTR is the code name for the 3DS and the random characters to distinguish one SD from others.
Example: `CTR-UCODKAJ`, `CTR-DOHWTXK` and `CTR-VKSHXKL`.

**Comment by SirNapkin1334** [comment] 2017-12-27 05:03
@pthfdr-42 remember, FAT32 discs can only have a certain amount of characters in their names, and what you suggested exceeds that. Plus, it's not that hard to add a `-1` to the end of the name to distinguish between multiple of the same system.

**Comment by pthfdr-42** [comment] 2017-12-27 06:14
>FAT32 discs can only have a certain amount of characters in their names
The limit is 11.The naming scheme I suggested used exactly 11 bytes.7 bytes (`CTR-SD-`) fixed and 4 bytes random.

>it's not that hard to add a -1 to the end of the name
But the problem is that every formatted FS should be unique, hence the random part, which should be enough.

**Comment by d0k3** [comment] 2017-12-27 17:42
Alright.... so, after some consideration: As you both see, everyone has a different opinion on how your SD cards should be named (I name mine [DEVICE][X]GB, as in "N3DS64GB"). The label naming tool is already there, so everyone can have their way. Introducing "smart" name presets means work that would better go elsewhere (as in: how often do you actually format your SD via GM9?).

I did, however, increase the char limit to 11 (from formerly 8). Closing this now...

**Closed by d0k3** 2017-12-27 17:42 UTC
