### ISSUE TITLE
In ntrboot mode, GM9 fails to automatically mount large SD card.

### ISSUE THREAD

**Issue by Cuphat** [d0k3/GodMode9#262] opened 2017-11-11 01:27 UTC
Using the latest commit, with the proper aeskeydb.bin compiled into it.

Most of the (small, ~4GB) SD cards seem to automatically mount fine. However, my main 3DS's 128GB card does not automatically mount when booting GM9 in ntrboot mode. Pressing R+B to remount the card works perfectly fine, however this is not something that you can do when GM9 is compiled with an autorun script.

One other relevant detail is the SD card has 2 EmuNANDs (RedNANDs).

**Comment by Derek1199** [comment] 2017-11-11 03:08
Is this from the master branch?

**Comment by Cuphat** [comment] 2017-11-11 03:20
Yes, master branch.

**Comment by Derek1199** [comment] 2017-11-11 04:26
Okay. I'll try to reproduce this.

**Comment by Derek1199** [comment] 2017-11-11 05:11
I also reproduced this. This is definately a bug.

**Comment by figgyc** [comment] 2017-11-11 11:09
is this only a problem in ntrboot mode?

**Comment by Derek1199** [comment] 2017-11-11 13:04
This also happens when booting it through firm0/1 too. However it's bootloader still works and boots the boot.firm on the SD card. Tested this placing GodMode9 as boot.firm on CTRNand and it still booted the payload on the SD card. But yeah this occurs on firm partition boots too.

**Comment by d0k3** [comment] 2017-11-11 15:06
Can you check if this also happens with the latest release (instead of building from the latest code)?

@angelsl - any chance this is caused by your recent changes to `sdmmc.c`?

**Comment by angelsl** [comment] 2017-11-11 15:09
@d0k3 Probably is.

I guess the timeout needs to be increased.

**Comment by Cuphat** [comment] 2017-11-11 16:42
I just tested and 1.4.3 release does not have this problem.

**Comment by urherenow** [comment] 2017-11-11 18:31
Timeout seems like a reasonable culprit. 128GB+ cards are considerably slower than 64GB <

**Comment by fox8091** [comment] 2017-11-11 19:01
Question is, how high up should we reasonably support? The 3DS supports up to a theoretical maximum of 2TB SD cards.

**Comment by Derek1199** [comment] 2017-11-11 19:04
@d0k3 I have a rednand that I made using GodMode9 many months ago. Lol. So given this,  it's probably what @angelsl did.

**Comment by d0k3** [comment] 2017-11-11 19:36
Okay, the timeout was the culprit, no other option... you'll need to wait a bit for the fix in master, cause the current work branch `new_make2` is not fully working yet.

If anyone wants to give it a try with an 128GB card, here's a testbuild:
https://transfer.sh/vvkkZ/GodMode9-v1.4.3-28-gdbfc99df-20171111193238.zip
(disfunctional atm: splash, aes_keydb.bin, hardcoded readme)

**Comment by Cuphat** [comment] 2017-11-12 00:10
I'm not actually able to download that build, clicking the download link just leads to an error.

**Comment by RShadowhand** [comment] 2017-11-12 17:38
You can try downloading it with wget, or any other download manager if you're on Windows. I can confirm wget works. I tried with IDM but it failed.

**Comment by d0k3** [comment] 2017-11-12 18:01
https://f.secretalgorithm.com/Xzapw/godmode9-v1.4.3-28-gdbfc99df-20171112175836.zip

You can also just download from @RShadowhand's superior transfer.sh fork ^

**Comment by Cuphat** [comment] 2017-11-12 21:00
Yeah, earlier yesterday transfer.sh just didn't work for me in any browser. It was working later last night/this morning though.

I tested that build and it works fine.

**Comment by d0k3** [comment] 2017-11-17 18:39
Fixed by https://github.com/d0k3/GodMode9/commit/83b2fba142ae011560caf59d1a13ff8dadcf24c1

**Closed by d0k3** 2017-11-17 18:39 UTC
