### ISSUE TITLE
[BUG] Black screen/No Backlight when booting into GodMode9 in Luma 10.2 with only one payload.

### ISSUE THREAD

**Issue by TheMasterOfMike** [d0k3/GodMode9#608] opened 2020-07-17 04:40 UTC
Basically, if you're attempting to boot into GodMode9 using Luma 10.2, and it is your only payload, you just get a black screen.

How to replicate this:

1. Make sure the console is running Boot9Strap and Luma 10.2.
2. Make sure that the only payload in luma/payloads/ is the GodMode9 payload.
3. Hold start on boot, it should remain a black screen and not start either the home menu or GodMode9.

We can also prove this isn't Luma3ds related issue simply by inserting a 10.1.3 firm into our payloads on 10.2 and holding start, you can check that yourself and it works fine.

Systems Tested On (not including all the systems in NH Discord):

- New Nintendo 2ds XL with Boot9Strap+Luma 10.2 running SysNand 11.13.0-45U and EmuNand 9.2.0-20U

- Nintendo 2ds with Boot9Strap+Luma 10.2 running SysNand 11.13.0-45U

**Comment by sthetix** [comment] 2020-07-17 04:43
I can confirm that this issue is true. We need a workaround to run Godmode9

**Comment by Oreo639** [comment] 2020-07-17 04:53
A workaround was already suggested here:
https://github.com/LumaTeam/Luma3DS/issues/1457

**Comment by TuxSH** [comment] 2020-07-17 10:37
Possible duplicate of https://github.com/d0k3/GodMode9/issues/578

**Comment by TheMasterOfMike** [comment] 2020-07-17 18:47
> Possible duplicate of #578

I think the issues are probably related, but I don't think it's a full on duplicate, as the one issue revolves around booting the GodMode9 firm from GodMode9, where as this issue involves just straight up booting the 3ds while holding start on Luma 10.2 with only a single payload.

**Comment by Lillievela** [comment] 2020-07-17 22:54
Upon trying this on mine, it is absurdly dim, my theory is the new brightness controls are causing it. Tested via standard old 3ds model

**Comment by TheMasterOfMike** [comment] 2020-07-17 23:49
I just learned that another portion of the issue can be no backlight running, while I do not personally have the backlight issue, it's common on NH discord along with the black screen.

**Comment by Swangtheugly** [comment] 2020-07-18 04:00
Hey all, I’ve recently purchased a New 2DS and successfully modded it. Though I know it’s been concluded that the issue is caused from the Luma update. I too can confirm that the update doesn’t agree with GodMode9. 

I’ve done my own tinkering, but can’t unfortunately produce any results. Though this is frustrating on my part since I wish to make digital versions of my Cartridge games, I hope a fix is found soon, I’d appreciate it immensely!

**Comment by TheMasterOfMike** [comment] 2020-07-18 15:15
> Hey all, I’ve recently purchased a New 2DS and successfully modded it. Though I know it’s been concluded that the issue is caused from the Luma update. I too can confirm that the update doesn’t agree with GodMode9.
> 
> I’ve done my own tinkering, but can’t unfortunately produce any results. Though this is frustrating on my part since I wish to make digital versions of my Cartridge games, I hope a fix is found soon, I’d appreciate it immensely!

There already is the workaround of either duplicating your GodMode9 payload or using a dummy payload to get into the chainloader.

But yeah, it's a GodMode9 issue, not a Luma issue.

**Comment by mozaka22** [comment] 2020-07-18 23:46
> > Hey all, I’ve recently purchased a New 2DS and successfully modded it. Though I know it’s been concluded that the issue is caused from the Luma update. I too can confirm that the update doesn’t agree with GodMode9.
> > I’ve done my own tinkering, but can’t unfortunately produce any results. Though this is frustrating on my part since I wish to make digital versions of my Cartridge games, I hope a fix is found soon, I’d appreciate it immensely!
> 
> There already is the workaround of either duplicating your GodMode9 payload or using a dummy payload to get into the chainloader.
> 
> But yeah, it's a GodMode9 issue, not a Luma issue.

could you explain in further detail? im not understanding "duplicating your GodMode9". do you mean all you have to do is create a duplicate file of godmode9, change the name and it'll work?

**Comment by TheMasterOfMike** [comment] 2020-07-19 00:54
> > > Hey all, I’ve recently purchased a New 2DS and successfully modded it. Though I know it’s been concluded that the issue is caused from the Luma update. I too can confirm that the update doesn’t agree with GodMode9.
> > > I’ve done my own tinkering, but can’t unfortunately produce any results. Though this is frustrating on my part since I wish to make digital versions of my Cartridge games, I hope a fix is found soon, I’d appreciate it immensely!
> > 
> > 
> > There already is the workaround of either duplicating your GodMode9 payload or using a dummy payload to get into the chainloader.
> > But yeah, it's a GodMode9 issue, not a Luma issue.
> 
> could you explain in further detail? im not understanding "duplicating your GodMode9". do you mean all you have to do is create a duplicate file of godmode9, change the name and it'll work?

All you have to even do is add a second payload really, any second payload works, for it will start the Luma chainloader (hell you could copy boot.firm into the payloads and it would work).

**Comment by Wolfvak** [comment] 2020-07-21 01:21
Tentatively fixed in https://github.com/d0k3/GodMode9/commit/30f0b004c23a7de10c1723c67dd684d71f7b7dfd.
There's still a race condition where GM9 wont properly boot from other code that performs screen deinit but doesnt wait for it to complete in new3DS, so in the future a 150ms delay will be added on boot for new3DS users.

**Closed by Wolfvak** 2020-07-21 01:21 UTC
Labels: bug

**Comment by Snajper89** [comment] 2020-08-08 08:38
It's not GodMode9 bug, it's Luma 10.2 bug, on Luma 10.1 GodMode9 1.9.1 works fine!
