### ISSUE TITLE
[BUG] ...Sleep Mode Seems to be broken. I cannot decrypt firms either.

### ISSUE THREAD

**Issue by linusrg1** [d0k3/GodMode9#657] opened 2020-12-04 22:32 UTC
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
I tried to decrypt a system firm and it did not work. I also tried to enter sleep mode in gm9 and that did not work either. 
* Give us clear steps to reproduce (when/how did it happen?).
Try to decrypt the firm used in the uninstall cfw part of 3ds.guide and try to put 3ds to sleep.
* Give us info about your system (where did it happen?).
I happened in the firm decrypt menu. And when I tried to enter sleep mode from anywhere in gm9.
* A photograph or even a short video of the bug happening is always helpful!

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS) N3DS
* Anything special about your console? (defects, custom modifications,...)
My 3ds is running in a Lazarus state.
* Bootloader (boot9strap/fastboot3ds) b9s
* Did you chainload GodMode9 via Luma? Yes I did.

**Comment by Wolfvak** [comment] 2020-12-05 21:51
Sleep mode is known to be broken in master and 1.9.2pre1, but it should be fixed in the mcuev branch if you wanna try it out.

**Comment by linusrg1** [comment] 2020-12-05 22:54
Ok and what about that firm thing. Mind trying it out?

**Comment by Wolfvak** [comment] 2020-12-06 17:46
I'm not sure what FIRM you tried to decrypt but I can't reproduce it (latest new3DS NATIVE_FIRM from an old3DS)

**Comment by d0k3** [comment] 2020-12-09 21:08
@linusrg1 - for sleep mode, can you try this test build?
https://f.secretalgorithm.com/edwL7/godmode9.firm

As for decrypting firms... can you give us more info? Maybe a screenshot of what happens when you try to decrypt and some instructions on how to find that FIRM?

**Comment by d0k3** [comment] 2020-12-23 14:00
Alright, this lacks info. The sleepmode issue is considered solved, as for the other one, feel free to reopen @linusrg1.

**Closed by d0k3** 2020-12-23 14:00 UTC
Labels: bug
