### ISSUE TITLE
Feature Request - beable to dump DSi Enhansed DSi game

### ISSUE THREAD

**Issue by Shadow322** [d0k3/GodMode9#105] opened 2017-07-04 09:57 UTC
I am unable to properly dump DSi White game carts

**Comment by d0k3** [comment] 2017-07-04 10:23
Duplicate of https://github.com/d0k3/GodMode9/issues/104

if you have problems dumping carts, describe your problem there.

**Closed by d0k3** 2017-07-04 10:23 UTC
