### ISSUE TITLE
godmode9 error in new 3ds 11.2k

### ISSUE THREAD

**Issue by kimsj531** [d0k3/GodMode9#20] opened 2017-01-14 14:38 UTC
I was trying to change my 3ds region, which is KOR, to USA but using godmode9 does not work. Every time I try,(changing secureinfoA) it shows 'CTRNAND load failed' and fails booting.
Godmode9 isn't working in 3ds 11.2k, and I hope you can fix this problem plz : )

**Comment by d0k3** [comment] 2017-01-14 16:24
Are you on A9LH? How do you boot GM9? Also, maybe provide a aeskeydb.bin file in root?

**Comment by kimsj531** [comment] 2017-01-15 08:41
Yes i'm on a9lh and also has every files in right place.
Not only me, but other korean are having trouble with this issue.-----Original Message-----

**Comment by kimsj531** [comment] 2017-01-15 09:02
Using Decrypt9 to overwrite secureinfoA instead of Godmode9 solved this problem :) 
Thanks for your help-----Original Message-----

**Comment by d0k3** [comment] 2017-01-15 14:06
I'd still like to have this solved in GM9... so, you say others with a KOR N3DS have the same problem? Everyone with a KOR N3DS? The exact error message and/or a screenshot would help, too. Also, can you try with aeskeydb.bin in root? You may get this file, f.e. from the guide.

**Comment by kimsj531** [comment] 2017-01-15 14:39
Well...I'm not an expert in 3ds hacking, but korean 3ds hacking bloggers found out that after editing hex codes with Godmode, n3ds korean version simply can't load CTRNAND. After editing hex codes, when I reboot my 3ds, it shows 'CTR NAND LOAD FAILED' error screen.

Sorry for no screenshots, but this is true and korean n3ds users are using Decrypt9 to change their region.
Thanks for your replies :)-----Original Message-----

**Comment by d0k3** [comment] 2017-01-15 16:12
Okay, there is a way you can help me. Can you retry this in GM9? You know, you can easily fix it. If it happens again, can you show me the good SecureInfo vs the bad one? And don't post that in the open. Send me a pm on freenode #Cakey or GBAtemp.

**Comment by d0k3** [comment] 2017-01-15 16:23
And, one more thing. If you don't have a screenshot, can you give me some more info on when this error message appears and what it looks like (background / font color, etc...)

**Comment by d3m3vilurr** [comment] 2017-01-15 17:08
ok. i readed korean blog post.
[this](http://qpspelrxjs23.blog.me/220910967724) post, right?
he naver explain why need that. just say do region change.

but,

1. you don't need region change until you want to access their region's eshop.
2. we already have too many way for overwriting secureinfo_a.
  - if you have hex editor, just use d9wip's dump/inject option.
  - always backup last working nand.
3. in my test, gm9 works normal in korean n3ds.

`ctr nand error` probably not related gm9 and I highly expect it's your fault.
so just restore nand from backup, then try another method.

**Comment by d3m3vilurr** [comment] 2017-01-16 02:20
and at yesterday, I tried region changes with [original guide](https://3ds.guide/region-changing) on my kor n3ds.
I haven't any problem.

**Comment by d0k3** [comment] 2017-01-16 09:31
Okay, thanks a lot, @d3m3vilurr! With GM9 confirmed working for region changing, on a KOR N3DS console, your issue looks a lot like either you did something wrong, there is something wrong in the tutorial you used or the cause of the issue is something else (= not GM9). I've also never seen that error message "CTR NAND LOAD FAILED".

I'm closing this now, but feel free to reopen if you still think GM9 is at fault and/or you can provide more information to this issue.

**Closed by d0k3** 2017-01-16 09:31 UTC
