### ISSUE TITLE
top screen not working on new 3ds IPS screen godmode v1.8.0

### ISSUE THREAD

**Issue by Littlemac123** [d0k3/GodMode9#538] opened 2019-09-20 17:57 UTC
on the newest update the top screen does not display anything and my last update was about a year ago and it was working fine before and I wish to get the new things in the new update so I hope it gets fixed

im using a new 3ds XL with a IPS screen on top and TN screen on bottom using the boot firm of godmode v1.8.0
https://cdn.discordapp.com/attachments/288361557044494337/624658802527961088/IMG_20190920_122409.jpg
this is what it looks like and it looks weird and glitchy and then just black

the top screen is working perfictly fine in luma 3ds menus and the 3ds homemenu

**Comment by Wolfvak** [comment] 2019-09-20 17:59
Duplicate of https://github.com/d0k3/GodMode9/issues/466

**Closed by Wolfvak** 2019-09-20 17:59 UTC
Labels: duplicate

**Comment by Littlemac123** [comment] 2019-09-20 18:01
> Duplicate of #466

but it booted fine its just the top screen is nor displaying

**Comment by Wolfvak** [comment] 2019-09-20 18:03
Yes, it's a screen init problem. Try the v1.7.1 release and if that one doesnt work either, please do come back.
