### ISSUE TITLE
top screen not working

### ISSUE THREAD

**Issue by zjthang** [d0k3/GodMode9#489] opened 2019-06-03 12:02 UTC
hi so recently i tried to update my godmode9 to the latest version, i followed everything on a youtube instructions video but now when i bootup while pressing start, i have the bottom screen but no top screen.. can someone explain to me what happened?? thank you very much

**Comment by zjthang** [comment] 2019-06-03 12:13
i got this problem when my system is on 11.9.0 (recently updated to 11.10.0) the problem still persists.. so far i have not seen anyone with a blank top screen

**Comment by d4rk7yp3** [comment] 2019-06-03 13:39
i have the (almost) same issue, except my bottom screen stays black after booting into godmode9...

**Comment by legoj15** [comment] 2019-06-03 17:44
You guys are expieriencing #466 
The solution is to install fastboot3DS https://github.com/d0k3/GodMode9/issues/466#issuecomment-480367345

**Comment by zjthang** [comment] 2019-06-06 15:01
> You guys are experiencing #466
> The solution is to install fastboot3DS [#466 (comment)](https://github.com/d0k3/GodMode9/issues/466#issuecomment-480367345)

hi ive just installed that but when is start im taken into a new screen now not godmode9 anymore and i cannot find a way to access godmode9 anymore

**Comment by zjthang** [comment] 2019-06-06 15:11
> > You guys are experiencing #466
> > The solution is to install fastboot3DS [#466 (comment)](https://github.com/d0k3/GodMode9/issues/466#issuecomment-480367345)
> 
> hi ive just installed that but when is start im taken into a new screen now not godmode9 anymore and i cannot find a way to access godmode9 anymore

nvrm i just fixed it turns out i just had to add a new payloads file in gm9 and put godmode9.firm inside

**Comment by d0k3** [comment] 2019-06-06 19:27
Duplicate of #466, as already pointed out.

**Closed by d0k3** 2019-06-06 19:27 UTC

**Comment by zjthang** [comment] 2019-06-09 06:46
> Duplicate of #466, as already pointed out.

hi im not sure if this is related but after installing fastboot, when i play pokemon sun,the game crashes halfway.. 
i used to be able to play the game smoothly without this probem before i installed fastboot.. do you know what the problem is?
it says error type: generic 
process ID: 42
process name: niji_loc
process title ID: 0x0004000000164800

address: 0x006b39d8
error code:0xc9604523
