### ISSUE TITLE
Feature Request: Command to Find Latest File Made With findnot

### ISSUE THREAD

**Issue by MyLegGuy** [d0k3/GodMode9#189] opened 2017-08-28 22:06 UTC
findnot is good for making multiple saves backups and stuff, but, to my knowledge, there's no scripting command that can find the file that was most recently made with a path from findnot.

Example:
I use a path found with findnot and the filename "aaa_???.sav" to create a file. I do this multiple times and get files with these names:
aaa_000.sav
aaa_001.sav
aaa_002.sav

I would like a command that would be able to find "aaa_002.sav".

---

If there really is no way of doing this right now, I've modified the findnot code to subtract 1 from the result.
```c
FRESULT fvx_findnewpath (TCHAR* path, const TCHAR* pattern) {
    strncpy(path, pattern, _MAX_FN_LEN);
    TCHAR* fname = strrchr(path, '/');
    if (!fname) return FR_DENIED;
    fname++;
    
    TCHAR* rep[16];
    u32 n_rep = 0;
    for (u32 i = 0; fname[i]; i++) {
        if (fname[i] == '?') {
            rep[n_rep] = &(fname[i]);
            *rep[n_rep++] = '0';
        }
        if (n_rep >= 16) return FR_DENIED;
    }
    if (!n_rep) return fvx_stat(path, NULL);
    
    while (fvx_stat(path, NULL) == FR_OK) {
        for (INT i = n_rep - 1; (i >= 0); i--) {
            if (*(rep[i]) == '9') {
                if (!i) return FR_NO_PATH; 
                *(rep[i]) = '0';
            } else {
                (*(rep[i]))++;
                break;
            }
        }
    }
    // Subtracts 1 from the result
    for (INT i = n_rep - 1; (i >= 0); i--) {
        if (*(rep[i]) == '0') {
            *(rep[i]) = '9';
        } else {
            (*(rep[i]))--;
            break;
        }
    }

    return FR_OK;
}
```
(Note that the command will set the variable to "aaa_999" if it finds "aaa_000".)
If you like it, I make a pull request with the command name being your choice.

**Comment by d0k3** [comment] 2017-08-28 23:01
So, what you want is a file "aaa_???.sav", with the highest possible number, correct? You can not tell if the file name was created via findnot, or if the user created that file, of course. And yes, the current scripting system actually does not allow that. Now, the above code would be largely a duplicate of already existing code, which is not  a good idea.

Let me think about this one for a bit...

**Comment by MyLegGuy** [comment] 2017-08-28 23:06
Yeah, that's exactly what I want.

**Closed** 2017-09-01 00:30 UTC

**Comment by d0k3** [comment] 2017-09-01 00:32
Testing is appreciated. As a remark to that - previously, 'find' was optimized for speed, and it would return anything that it can find quickly. Now, it will always return teh alphanumeric last match.
