### ISSUE TITLE
[BUG] SD Space Remaining Fails to Update

### ISSUE THREAD

**Issue by SNBeast** [d0k3/GodMode9#591] opened 2020-03-19 12:25 UTC
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
* Give us clear steps to reproduce (when/how did it happen?).
* Give us info about your system (where did it happen?).
* A photograph or even a short video of the bug happening is always helpful!

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
* Anything special about your console? (defects, custom modifications,...)
* Bootloader (boot9strap/fastboot3ds)
* Did you chainload GodMode9 via Luma?
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[x] I have read the information above

The bug is that the free space on an SD card does not update upon insertion if a large amount of data was deleted from another device.

The bug can be observed when deleting a large amount of data from the SD card on another device; for example, if you dump a lot of carts, unmount and eject the SD, insert it into a PC, copy the dumps then delete them from the SD, then unmount and eject the SD from the PC and re-insert it into the same 3DS with GM9 and remount it. The amounts of used and free space do not update, which can prevent dumping more carts even if there is actually enough space.

The bug is remedied by entering a 3DS program (for example, Software in System Settings) that updates the amount of free space.

My system is an N3DS with boot9strap, and GM9 is loaded with the Luma chainloader. I doubt that my SD card has defects, considering it's a new card from a reliable source.

**Comment by Wolfvak** [comment] 2020-03-28 14:27
Can't reproduce: I have 1.9GB free in my SD card and made two NAND backups to it (954MB each, O3DSXL), then unmounted and ejected the SD from GM9, moved it to a Windows laptop and deleted one of the backups. After remounting the SD card in GM9, the drive info shows up as 1.0GB free (correct) and it allows me to create another backup.

**Comment by TurdPooCharger** [comment] 2020-04-14 17:42
@SNBeast, check if your SD card is fake, faulty, or dying.
1. Copy everything off the SD card to a computer.
2. [Quadruple reformat](https://gbatemp.net/threads/new-2ds-xl-microsd-card-error.534480/#post-8569741).
3. Full Write + Verify the _empty_ card with [H2testw](https://3ds.hacks.guide/h2testw-(windows).html']H2testw). **Do not skip**.

**Comment by d0k3** [comment] 2020-04-15 12:30
@SNBeast - try what @TurdPooCharger wrote. Even more so, be careful trusting this SD card with important data. Even if your card is from a reliable source and new, s**t happens. I had SD cards fail, too, and I never bought shady ones.

**Comment by d0k3** [comment] 2020-04-23 06:37
Closing this due to lack of info. @SNBeast - you may still add info here, I'll get notified.

**Comment by SNBeast** [comment] 2020-07-08 21:32
Well I finally got around to testing the microSD, and it passes h2testw full-space testing, and I've yet to have another error with it.

**Comment by d0k3** [comment] 2020-08-14 11:22
Looks like we will need to look into this further.

Can you give us a screenshot of the ouput of R+A on SD drive (0:) -> Show drive info? A photograph helps, too, of course.

**Comment by d0k3** [comment] 2020-10-12 22:11
Alright, closing this, thankyou!

**Closed by d0k3** 2020-10-12 22:11 UTC
Labels: bug
