### ISSUE TITLE
Godmode9 not working on 11.10

### ISSUE THREAD

**Issue by hunttung** [d0k3/GodMode9#487] opened 2019-05-31 15:20 UTC
all the firms and payloads are in the right folders, luma>payloads> Godmode9.firm. no matter what it will not show up.

**Comment by Ectalite** [comment] 2019-05-31 15:47
Same here, can't boot it  and  it is freezing

**Comment by hunttung** [comment] 2019-05-31 16:04
Damn! Nintendo!

**Comment by aspargas2** [comment] 2019-06-01 04:03
This has nothing to do with 11.10. The latest GodMode9 not working on some systems is a [known issue](https://github.com/d0k3/GodMode9/issues/466). Temporarily using [GodMode9 1.7.1](https://github.com/d0k3/GodMode9/releases/tag/v1.7.1) instead should fix it.

**Comment by hunttung** [comment] 2019-06-01 14:43
Will it ever get fixed?

**Comment by d0k3** [comment] 2019-06-02 07:55
Assumed duplicate of https://github.com/d0k3/GodMode9/issues/466

GodMode9 does not care about the system version installed. OS version 11.10 can't have anything to do with it.

**Closed by d0k3** 2019-06-02 07:55 UTC
