### ISSUE TITLE
Feature Request: Add If Statements to scripting

### ISSUE THREAD

**Issue by ZetaDesigns** [d0k3/GodMode9#156] opened 2017-08-13 13:20 UTC
Title is self-explanatory. Adding if statements in the script feature.

**Comment by d0k3** [comment] 2017-08-13 17:38
Yup, that's planned. Thank you!

**Comment by d0k3** [comment] 2017-08-15 01:17
Actually: duplicate of #129 - if you have anything to add, continue there.

**Closed by d0k3** 2017-08-15 01:17 UTC
Labels: enhancement
