### ISSUE TITLE
[BUG] A long delay of the gamecart drive

### ISSUE THREAD

**Issue by HIDE810** [d0k3/GodMode9#560] opened 2019-10-27 15:35 UTC
This is a continuation from https://github.com/d0k3/GodMode9/issues/550.

Boot issue via fastboot3ds was fixed by commit https://github.com/d0k3/GodMode9/commit/2b0545368528af746ac0bb77b00eee5d1d2cdd28. But when I select the gamecart drive, it still has the delay.

**Comment by Ammako** [comment] 2019-10-27 21:16
The delay is excruciatingly long when R4i Gold 3DS+ is inserted (in flashcart mode), on 1.8.0 it took less than 1 second to load. I don't have any issues with any other carts.

**Comment by d0k3** [comment] 2019-10-27 21:49
One more for @dratini0.

@HIDE810 & @Ammako - did you also test this with the latest test build?

**Comment by Ammako** [comment] 2019-10-27 21:51
I did, yes. I don't actually see any difference between it and 210ea69.

**Comment by Ammako** [comment] 2019-10-28 05:41
Behavior seems inconsistent; earlier, when I left a comment, the cartridge was always being scanned on boot, resulting in a delay until it was done scanning the cart. But now, still on the same build and same setup, for some reason it now no longer scans the cart on boot, and only scans on-demand when accessing the C: drive, or when I take out/reinsert the cart.

The only thing that really changed is that I'm not using the same SD card right now as I was using earlier, but I don't know why that would make a difference.

**Comment by HIDE810** [comment] 2019-10-28 15:29
> @HIDE810 & @Ammako - did you also test this with the latest test build?
https://f.secretalgorithm.com/Js57/godmode9.firm

This doesn't seem to include https://github.com/d0k3/GodMode9/commit/2b0545368528af746ac0bb77b00eee5d1d2cdd28.

@Ammako - I think so too.

**Comment by d0k3** [comment] 2019-10-28 20:10
Okay, may bad. And, good catch, @HIDE810 .

Do the issues still persisit with this build?
https://f.secretalgorithm.com/M0TwG/godmode9.firm


> Behavior seems inconsistent; earlier, when I left a comment, the cartridge was always being scanned on boot, resulting in a delay until it was done scanning the cart. But now, still on the same build and same setup, for some reason it now no longer scans the cart on boot, and only scans on-demand when accessing the C: drive, or when I take out/reinsert the cart.
> 
> The only thing that really changed is that I'm not using the same SD card right now as I was using earlier, but I don't know why that would make a difference.

As for this. See, gamecarts are black magick. In that case, the cart slot is not initialized until the console is running for x ms (x > 1000?). If we leave the splash screen early, GM9 detects (1) no cart inside the slot (2) a cart in the slot a few msec after. Initializing that other SD card may have had a slightly longer delay, thus the difference.

Now, GM9 should not initialize the cart on boot. Even if it's just 3sec, that's too long. Carts should only be detected when switching or when entering the drive. So... does the new build work as intended?

**Comment by Ammako** [comment] 2019-10-28 20:32
Makes sense. It does do what it's supposed to do, yes.

**Comment by d0k3** [comment] 2019-10-29 17:50
Well, does the cart init on boot for you (which it shouldn't!), @Ammako ? And, by certain games, do you mean just the R4i Gold 3DS+flashcart or more?

Also, @HIDE810 - note that the last test build also had an attempted fix for that delay. Can you test?

**Comment by Ammako** [comment] 2019-10-29 17:59
Yes, with the increased splash screen time, it prevents the init on boot. And sorry, I didn't think to test the long delay issue, but that fix does result in much faster initialization for me, as well.

**Comment by HIDE810** [comment] 2019-10-29 22:38
> Do the issues still persisit with this build? Please test, @Ammako & @HIDE810
https://f.secretalgorithm.com/M0TwG/godmode9.firm

Yes. The delay was largely improved.

**Comment by d0k3** [comment] 2019-11-01 23:31
So, you two tell me, @Ammako and @HIDE810, can we close this?

**Comment by HIDE810** [comment] 2019-11-02 03:50
I'm okay. I'll leave this to @Ammako .

**Comment by Ammako** [comment] 2019-11-02 04:06
Yeah, sorry for the confusion. Everything's fine on my end, this can be closed.

**Closed** 2019-11-02 11:43 UTC
Labels: bug
