### ISSUE TITLE
[Bug] NDS Game Card freezing device

### ISSUE THREAD

**Issue by sora10pls** [d0k3/GodMode9#104] opened 2017-07-03 17:36 UTC
Does not happen with the latest stable release.

If GodMode9 is running and a NDS Game Card is inserted while GodMode9 is running, attempting to load the `[C:] GAMECART` drive freezes the device.

If GodMode9 is running and a NDS Game Card was already inserted prior to GodMode9 being run, GodMode9 is able to load the `[C:] GAMECART` drive, but immediately freezes when the `.nds` files are shown (non-trimmed and trimmed).

This does not happen with 3DS Game Cards.

**Comment by d0k3** [comment] 2017-07-03 19:07
So, if it does not happen with the latest stable release, what release does it happen on? Did you try the latest nightly?

**Comment by sora10pls** [comment] 2017-07-03 19:13
It does happen with the latest nightly. Not sure which commit caused this issue, though.

**Comment by d0k3** [comment] 2017-07-04 00:01
Okay, I cannot reproduce it. I've only got a DSTT here for testing. Does this happen always or soemtimes? Also, does it happen for all your carts?

**Comment by sora10pls** [comment] 2017-07-04 00:16
I am using the latest nightly from that site.

I've tested using the following games:
- Pokemon Diamond
- Pokemon Platinum
- Pokemon HeartGold
- Pokemon SoulSilver
- Pokemon White
- Pokemon Black 2
- Mario & Sonic at the Winter Olympic Games
- Pokemon Mystery Dungeon: Explorers of Sky

This is a consistent bug that happens every time. Since you said you have a DSTT for testing, when I'm home, I could try my R4i Gold RTS and see if it happens with that as well.

**Comment by d0k3** [comment] 2017-07-04 00:28
To my knowledge, these are all pretty big games. Do you have any smaller carts you can test with?

**Comment by sora10pls** [comment] 2017-07-04 03:14
Yeah, file size seems to be the cause of this. The following games worked:

- Super Mario 64 DS (16MB)
- Sim City DS (64MB)
- The Sims 2 Castaway (16MB)

Tested with a few other Game Cards, can also confirm that the games listed below also freeze the device:
- Mario & Sonic at the Olympic Games
- Mario & Luigi: Bowser's Inside Story

GodMode9 detects both of the Game Cards' ROMs as 128MB, and all the other games listed in my previous comment were 128MB+ in file size.

**Comment by Shadow322** [comment] 2017-07-04 10:29
Well I dump my copy of System FLAW and then place it on my Evoi and try it in DSi mode and it says DSi data is missing and says boot into DS mode to boot the game

**Comment by d0k3** [comment] 2017-07-04 11:31
Okay, @Shadow322 - try the last two stable releases from here and the latest nightly:
http://d0k3.secretalgorithm.com/

If the problem persists, open a new issue with a detailed description of the error.

**Comment by d0k3** [comment] 2017-07-04 11:45
@sora10pls - we will need to test earlier builds to find out where the error first occured. Can you try these, in order, to pinpoint the exact commit it happened on?

https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170608-164609.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170619-034605.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170621-234547.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170625-234546.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170628-234547.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170701-234546.zip

Once you got one that doesn't work, there's no need to try further. I'll have to provide more builds to test then.

**Comment by sora10pls** [comment] 2017-07-04 17:00
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170608-164609.zip -- **works**
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170619-034605.zip -- **works**
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170621-234547.zip -- **does not work**
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170625-234546.zip -- **does not work**
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170628-234547.zip -- **does not work**
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170701-234546.zip -- **does not work**

So the issue only exists in https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170621-234547.zip or later.

**Comment by d0k3** [comment] 2017-07-04 18:28
That commit can't cause this... but we will get behind it.

Can you try these builds?
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170620-014607.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170621-021610.zip
https://d0k3.secretalgorithm.com/GodMode9/GodMode9-20170621-120049.zip

**Comment by d0k3** [comment] 2017-07-04 19:07
Okay... I may have it fixed now...

@sora10pls please try this test build, tell me if it works again:
https://transfer.sh/ZwxiX/GodMode9-20170704-190723.zip

@Shadow322 - try this test build, too, please. I think it will also fix your issue.

**Comment by sora10pls** [comment] 2017-07-04 19:46
Apologies for no responses for a while, but I can say that the test build has indeed fixed my issue. Has no issues loading my NDS or 3DS Game Cards. :)

**Comment by d0k3** [comment] 2017-07-05 08:24
Okay, @sora10pls - next problem before I close this. Can you reboot with an NDS cart inserted? Or does it freeze in that case?

**Comment by sora10pls** [comment] 2017-07-05 17:26
Yeah, reboot seems to be broken when there's a NDS Game Card inserted. Poweroff seems to have the same issue.

**Comment by d0k3** [comment] 2017-07-05 23:02
Okay, I guess I fixed that, too. Can you try this test build?
https://transfer.sh/TFOa8/GodMode9-20170705-230036.zip

**Comment by sora10pls** [comment] 2017-07-06 15:58
Was indeed fixed.

**Comment by d0k3** [comment] 2017-07-06 16:04
Thanks!

**Closed** 2017-07-06 16:04 UTC
