### ISSUE TITLE
"Cart init failed!" on DSi development cartridge

### ISSUE THREAD

**Issue by TrashBandatcoot** [d0k3/GodMode9#477] opened 2019-04-26 14:26 UTC
This issue has already been discussed with d0k3 himself and with Voodooween (the owner of this cartridge).
Anyway, to keep up...
Voodooween owns a DSi "SystemUpdater" cartridge that can swap regions and upgrade/downgrade to v1.4. However, we've been going through a lot of trouble by getting the cartridge dumped. 

Wood Dumper & decrypt9wip find the cartridge, but make a bad dump and GodMode9 just refuses to find the cartridge at all. ("Cart init failed!" "A to continue" "GAMECART (EMPTY)") According to Voodooween, this is not a cart contact problem, and really is an issue with GodMode9.
So um, yeah, we're both stuck in a hole now... There's not much we can do.

**Comment by Wolfvak** [comment] 2019-04-26 14:30
It's not so much an "issue with GodMode9" - it probably does realize there's a cart in there, but something goes wrong during initialization (similar to how it can go wrong when there's a bad contact on a regular cart) and simply refuses to acknowledge it.

Is there any documentation on these carts? Without any there's not much we can do.

**Comment by Wolfvak** [comment] 2019-04-26 17:56
Duplicate of https://github.com/d0k3/GodMode9/issues/457

**Closed by Wolfvak** 2019-04-26 17:56 UTC
