### ISSUE TITLE
[BUG] ABGSave settings not showing

### ISSUE THREAD

**Issue by collinsem32** [d0k3/GodMode9#696] opened 2021-04-02 03:12 UTC
O3DS 
when trying to dump abgsave the abgsave settings don't show up. It happens every time without fail and I don't know what to do to fix it.

**Comment by d0k3** [comment] 2021-04-02 11:05
Can you give us more details? What exactly did you try to to do? On what file?

**Comment by collinsem32** [comment] 2021-04-02 13:02
Absolutely. I have pkmn red save file im trying to access. I hold start and power to open gm9. Then I go to the virtual section, then I click on abgsave.bin but it only gives my options to open in hex, view details, and copy to gm9/out

**Comment by d0k3** [comment] 2021-04-02 16:20
Could you upload the agbsave.bin file somewhere? Don't worry, there's no copyrighted data in there and there's only so much identifying info in there like your username.

**Comment by collinsem32** [comment] 2021-04-02 18:30
https://filebin.net/9qedwrlqzrio3ein

lmk if that works I uploaded the file there.

**Comment by d0k3** [comment] 2021-04-04 10:06
Alright, that worked. Now, there's no GBA save in there - the file looks like it was never written to. You know that you need to start a GBA game first and save at leats once before anything turns up in the `agbsave.bin` partition?

**Comment by collinsem32** [comment] 2021-04-04 13:25
Yes I know that but I have saved multiple times and still nothing shows up. Maybe the save is getting wrote to the wrong place?

**Comment by d0k3** [comment] 2021-04-04 17:17
Did you actually get that agbsave.bin file from the S:/ drive? Did you properly close that GBA game (power button)? Anything else that could have gone wrong?

**Comment by collinsem32** [comment] 2021-04-04 17:24
These are the steps I took. 
1st. Saved the game using the in game save function. 

2nd. Closed out of the game. Pressed home button closed the game. 

3rd. Powered down the 3ds 

4th. Started it up holding power and start to open gm9

5. Went to the virtual folder

6. Clicked on the abgsave.bin

**Comment by d0k3** [comment] 2021-05-01 13:43
Is the issue still happening, @collinsem32? I can't reproduce it here, and for all that I know it shouldn't be happening. If it still happens, try opening the GBA game again, saving again, closing it again, and booting back to GM9. Does it work now?

**Comment by Ammako** [comment] 2021-05-08 12:35
> I have pkmn red save file im trying to access.

FireRed? Or do you actually mean Red?

**Comment by d0k3** [comment] 2021-05-09 10:29
I think @collinsem32 is mia, or has his issue already resolved. I'm closing this for the time being, but feel free to continue writing here or reopen this. I will get a notification.

**Closed by d0k3** 2021-05-09 10:29 UTC
Labels: bug

**Comment by yasingunaydiin** [comment] 2025-02-02 14:07
Issue is happening to me.
