### ISSUE TITLE
[BUG] BlackScreeb when opening

### ISSUE THREAD

**Issue by davidcc73** [d0k3/GodMode9#614] opened 2020-07-27 21:00 UTC
I have  a new 3ds XL from Europe
After I update my luma3ds to the version v10.2 the godmode9 stopped working when I press the start during the boot, the 3ds only shows a black screen, I have to hold the power button to make it shut down. 
I tried to use de version v1.7.1 of godmod9 and it worked.

* Bootloader boot9strap
* Did you chainload GodMode9 via Luma? yes
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.* yes

**Have you actually read this?**
[yes] I have read the information above

**Comment by Wolfvak** [comment] 2020-07-27 21:05
Duplicate of #612 
Read the solution provided there.

**Closed by Wolfvak** 2020-07-27 21:05 UTC
Labels: bug
