### ISSUE TITLE
Enhancement : Accurate file timestamp for file details

### ISSUE THREAD

**Issue by SvenDaHacker64** [d0k3/GodMode9#103] opened 2017-07-01 17:24 UTC
When copying files from CTR NAND or game's RomFS to FatFS image (SD card), it always shows "31/12/2016 23:00" on 'Date modified' section of the files shown in this screenshot: 
![screenshot 2017-07-01 17 39 42](https://user-images.githubusercontent.com/29345291/27763933-3d1e0172-5e85-11e7-8b5c-4ee946b1ad1c.png)

It doesn't really bother me with inaccurate date that way.

That would be nice if it shows current time/date detail for newely created files.

Since the clock preserves even it's turned off because of battery still running, would that be possible to fetch current date/time information and save the detail to created/modified file (export files to 0:/gm9out for example) while running ARM9/FIRM before OS initialises? It's just like a clock stored in computer's BIOS using coin battery.
Aside from PTM:GetSystemTime sysmodule, it would be impossible to run as it needs to be on operating system.

So it would be easy to tell when was the last exact time I backed up my NAND.

**Comment by d0k3** [comment] 2017-07-01 18:24
Your correct, the clock is somewhere, but we have no idea where on ARM9. Also, no access to system functions of course.

So, not possible. If we ever get access, files will have the correct timestamp, of course. 

On copy / move operations, we may be able to preserve the original file timestamp - think this would help? If so, I may think about it.

**Comment by SvenDaHacker64** [comment] 2017-07-02 09:39
I see, seems to be difficult where to pinpoint the clock...

Oh yeah ,that too, copying file to new location even it's originally on SD card affects the file timestamp. It also happens with FBI or CTRXplorer that uses timestamp to be current time and date.

**Comment by fox8091** [comment] 2017-07-03 05:50
Why not run a small stub payload on the ARM11 that just passes the time and date over PXI?

**Comment by d0k3** [comment] 2017-07-03 10:07
The problem is not that we don't have access to ARM11, but that the OS is not running and we have no access to system functions. Proper timestamps will be coming once we have proper access to the clock. Closing this now...

**Closed by d0k3** 2017-07-03 10:07 UTC
