### ISSUE TITLE
godmode9 stuck on booting screen when loading for the first time 

### ISSUE THREAD

**Issue by billylambley** [d0k3/GodMode9#603] opened 2020-06-06 05:26 UTC
I have followed the gbatemp guide to installing cfw on my 3dsXL i gaet to the part where i openup godmode9 and it just says booting i have tried the latest version aswell as 1.8.1 and 1.7.1 but the same problem happens i am using luma i have tried resetting the time and date but still nothing i have tried loading fastbootloader but nothing happens when i hold start when starting the console it just goes to the home screen

**Comment by d0k3** [comment] 2020-06-30 17:06
We will need more info. Can you provide screenshots? Photos of your screen are okay as well, of course.

**Comment by d0k3** [comment] 2020-07-07 20:21
Info missing, so I'm closing this. Feel free to reopen if you can add more info or think this is not solved, @billylambley.

**Closed by d0k3** 2020-07-07 20:21 UTC
Labels: bug

**Comment by loki2199** [comment] 2020-10-21 19:14
Hey guys. After long time of researching this error i finally found someone describing the same error than i have. I did the 3ds haxxs guide and everything work well until i came to the point where i should start godmod9. Its not the problem with the black screen or that the chainloader of luma. To test it out i even tried to load it with fastboot and it is still the same. When i load godmode9 i see the starting screen where it shows the number of version and release date and in the right bottom corner it says booting. But doesnt matter how long i wait, nothing happens. So it literally stucks in loadscreen. Any idea what I have done wrong. I have an old 3ds XL. I updated to the latest software befor doing all the steps.

**Comment by d0k3** [comment] 2020-10-21 21:12
Broken buttons maybe?

**Comment by loki2199** [comment] 2020-10-21 21:50
No all buttons work as intended. I tried with luma v9.0. I triplechecked if i miss out on anything but i have done all steps in the guide.

**Comment by alphanoopy** [comment] 2022-03-25 15:59
i've also encounter with that problem. My fix is try , power on without sd and put back in the home screen menu and then power off . Don't take out the sd card and try launching godmode9 again , it is works for me hope that works for you :)
