### ISSUE TITLE
Can't mount savedata "public.sav" as FAT-image

### ISSUE THREAD

**Issue by ishad0w** [d0k3/GodMode9#147] opened 2017-08-08 07:10 UTC
1.2.8 - works as expected

**Comment by ahoischen** [comment] 2017-08-08 07:16
Duplicate of #145 and #142. The latest nightly has the fix.

**Comment by d0k3** [comment] 2017-08-08 09:41
It's true, I derped, and with a really important feature, too :/. Fix-release coming later today.

**Closed by d0k3** 2017-08-08 09:41 UTC
