### ISSUE TITLE
Menus on bottom screen do not appear

### ISSUE THREAD

**Issue by SammyD2002** [d0k3/GodMode9#473] opened 2019-03-31 23:40 UTC
Hello. I recently installed the anniversary edition of GodMode9 on my New Nintendo 3ds XL running Firmware 11.9.0-42U with Luma CFW 9.1. When running GodMode9, I noticed something odd. None of the menus appeared on the bottom screen when invoked. They're still there and functional, but I just can't see them. This did not occur on version 1.71 of GodMode9, and persists across installs with the package downloaded two separate times. Can you please help me?

**Comment by Wolfvak** [comment] 2019-03-31 23:40
Duplicate of #466

**Closed by Wolfvak** 2019-03-31 23:40 UTC
